module.exports = [
  {
    name: "calc",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/calc.c",
    language: "C",
  },
  {
    name: "byteswap",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/byteswap.c",
    language: "C",
  },
  {
    name: "file",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/file.c",
    language: "C",
  },
  {
    name: "func",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/func.c",
    language: "C",
  },
  {
    name: "hash",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/hash.c",
    language: "C",
  },
  {
    name: "help",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/help.c",
    language: "C",
  },
  {
    name: "hist",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/hist.c",
    language: "C",
  },
  {
    name: "input",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/input.c",
    language: "C",
  },
  {
    name: "label",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/label.c",
    language: "C",
  },
  {
    name: "lib_calc",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/lib_calc.c",
    language: "C",
  },
  {
    name: "listfunc",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/listfunc.c",
    language: "C",
  },
  {
    name: "matfunc",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/matfunc.c",
    language: "C",
  },
  {
    name: "math_error",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/math_error.c",
    language: "C",
  },
  {
    name: "opcodes",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/opcodes.c",
    language: "C",
  },
  {
    name: "poly",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/poly.c",
    language: "C",
  },
  {
    name: "qfunc",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/qfunc.c",
    language: "C",
  },
  {
    name: "str",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/str.c",
    language: "C",
  },
  {
    name: "symbol",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/symbol.c",
    language: "C",
  },
  {
    name: "zmod",
    project: "C-style arbitrary precision calculator",
    projectUrl: "https://github.com/lcn2/calc",
    license: "LGPL",
    licenseUrl: "https://github.com/lcn2/calc/blob/master/COPYING-LGPL",
    source: "https://raw.githubusercontent.com/lcn2/calc/master/zmod.c",
    language: "C",
  },
]
